### ISSUE TITLE
BadRequest Error

### ISSUE THREAD

**Issue by ehalsey** [IntuitDeveloper/SampleApp-CRUD_.Net_Oauth2#1]
https://github.com/IntuitDeveloper/SampleApp-CRUD_.Net_Oauth2/blob/master/SampleApp_CRUD_.Net/SampleApp_CRUD_.Net/TestQBOCalls.cs#L246

**Comment by nimisha84** [comment]
This is a valid error. Some field/prop need to be set/modified bases on the company locale and settings you have. Please enable logging in the code as suggested to log request and response. Then get details of the request to see which one is failing and see the bad response details on the response logs. The logs will tell you the exact error.

**Comment by Newcastle94** [comment]
web.config had the clientSecret key missing the L - entered as cientSecret.

**Comment by nimisha84** [comment]
Are you sure?
https://github.com/IntuitDeveloper/SampleApp-CRUD_.Net_Oauth2/blob/master/SampleApp_CRUD_.Net/SampleApp_CRUD_.Net/Web.config 
I see the key is correct.
